### ISSUE TITLE
error: RETRY PAGE PLEASE

### ISSUE THREAD

**Issue by Hamroyev** [Gemorroj/gmanager#2]
what i do for fix it?

**Comment by Hamroyev** [comment]
Warning: require(/storage/ssd3/679/8329679/public_html/Free/775476625/khamroev/gmanager-master/vendor/autoload.php): failed to open stream: No such file or directory in /storage/ssd3/679/8329679/public_html/Free/775476625/khamroev/gmanager-master/index.php on line 21 Fatal error: require(): Failed opening required '/storage/ssd3/679/8329679/public_html/Free/775476625/khamroev/gmanager-master/vendor/autoload.php' (include_path='.:/usr/share/pear:/usr/share/php') in /storage/ssd3/679/8329679/public_html/Free/775476625/khamroev/gmanager-master/index.php on line 21
it's error

**Comment by Gemorroj** [comment]
install composer deps, or use precompiled build https://github.com/Gemorroj/gmanager/releases/download/0.9b/gmanager-v0.9b-php7.zip
